//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TEST_GLOBALHITSSEntities1 : DbContext
    {
        public TEST_GLOBALHITSSEntities1()
            : base("name=TEST_GLOBALHITSSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<TIPO_IDENTIFICACION> TIPO_IDENTIFICACION { get; set; }
    
        public virtual int SP_CLIENTE_CAMBIO_ESTADO(Nullable<long> strdbid)
        {
            var strdbidParameter = strdbid.HasValue ?
                new ObjectParameter("strdbid", strdbid) :
                new ObjectParameter("strdbid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CLIENTE_CAMBIO_ESTADO", strdbidParameter);
        }
    }
}
