//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIPO_IDENTIFICACION
    {
        public TIPO_IDENTIFICACION()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public long dbid { get; set; }

        [Display (Name ="Tipo de Identificacion")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
    }
}
