//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVR_GlobalHitss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public long dbid { get; set; }
        public long dbidTipoIdentificacion { get; set; }
        public string Nombre { get; set; }
        public string Numero_identificacion { get; set; }
        public string email { get; set; }
        public long Movil { get; set; }
        public string Direccion { get; set; }
        public string Direccion_Instalacion { get; set; }
        public Nullable<System.DateTime> Fechacreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int Estado { get; set; }
    
        public virtual TIPO_IDENTIFICACION TIPO_IDENTIFICACION { get; set; }
    }
}
